# Generated by Django 4.1.3 on 2022-12-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_number', models.IntegerField(blank=True, default=0)),
                ('midfielder_number', models.IntegerField(blank=True, default=0)),
                ('defender_number', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ManyToManyField(related_name='line_up', to='wc_line_up_maker.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('shirt_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('flag', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SquadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='squad_list', to='wc_line_up_maker.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='squad_list', to='wc_line_up_maker.squad')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player', to='wc_line_up_maker.squad'),
        ),
        migrations.CreateModel(
            name='LineUpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_up', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='line_up_list', to='wc_line_up_maker.lineup')),
                ('player', models.ManyToManyField(related_name='line_up_list', to='wc_line_up_maker.player')),
                ('position', models.ManyToManyField(related_name='line_up_list', to='wc_line_up_maker.position')),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='squad',
            field=models.ManyToManyField(related_name='line_up', to='wc_line_up_maker.squad'),
        ),
        migrations.CreateModel(
            name='FormationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='formation_template', to='wc_line_up_maker.formation')),
                ('position', models.ManyToManyField(related_name='formation_template', to='wc_line_up_maker.position')),
            ],
        ),
    ]
