# Generated by Django 4.1.3 on 2022-12-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='abbreviation',
            field=models.CharField(default='GK', max_length=20),
            preserve_default=False,
        ),
    ]
