# Generated by Django 4.1.3 on 2022-12-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0002_position_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationtemplate',
            name='position',
        ),
        migrations.AddField(
            model_name='formationtemplate',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='formation_template', to='wc_line_up_maker.position'),
            preserve_default=False,
        ),
    ]
