# Generated by Django 4.1.3 on 2022-12-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0003_remove_formationtemplate_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='squad',
        ),
        migrations.AddField(
            model_name='lineup',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='line_up', to='wc_line_up_maker.formation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineup',
            name='squad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='line_up', to='wc_line_up_maker.squad'),
            preserve_default=False,
        ),
    ]
