# Generated by Django 4.1.3 on 2022-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0007_remove_formation_creator_id_delete_squadlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='creator_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
