# Generated by Django 4.1.3 on 2022-12-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0008_formation_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineuplist',
            name='player',
        ),
        migrations.RemoveField(
            model_name='lineuplist',
            name='position',
        ),
        migrations.AddField(
            model_name='lineuplist',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='line_up_list', to='wc_line_up_maker.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineuplist',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='line_up_list', to='wc_line_up_maker.position'),
            preserve_default=False,
        ),
    ]
