# Generated by Django 4.1.3 on 2022-12-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wc_line_up_maker', '0010_lineuptemplate_delete_lineuplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='lineup',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
