# Generated by Django 4.1.3 on 2023-02-08 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wc_line_up_maker', '0011_rename_creator_id_formation_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='formation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='line_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
